AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'ruby_llm_source/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ModuleLength:
  Max: 250

Layout/LineLength:
  Max: 120

# The alias file intentionally uses a hyphen to match gem naming
Naming/FileName:
  Exclude:
    - 'lib/ruby_llm-responses_api.rb'

# Development dependencies in gemspec is fine for a gem
Gemspec/DevelopmentDependencies:
  Enabled: false

# Empty block is intentional in streaming test
Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'

# Duplicate branches are sometimes clearer than complex conditionals
Lint/DuplicateBranch:
  Enabled: false
